// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSite.Models;

namespace MovieSite.Migrations
{
    [DbContext(typeof(FilmDataContext))]
    [Migration("20220202005855_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieSite.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmID = 1,
                            CategoryID = 5,
                            Director = "George Miller",
                            Edited = false,
                            Notes = "Great Movie",
                            Rating = "PG",
                            Title = "Happy Feet",
                            Year = 2006
                        },
                        new
                        {
                            FilmID = 2,
                            CategoryID = 4,
                            Director = "Christopher Nolan",
                            Edited = false,
                            Notes = "Crazy Movie",
                            Rating = "PG-13",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            FilmID = 3,
                            CategoryID = 12,
                            Director = "Marc Webb",
                            Edited = false,
                            Notes = "Funny and Sad Movie",
                            Rating = "PG-13",
                            Title = "500 Days of Summer",
                            Year = 2009
                        });
                });

            modelBuilder.Entity("MovieSite.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Action/Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Action/Thriller"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Action/Sci-fi"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Family/Adventure"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Family/Comedy"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Family/Drama"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "Horror/Comedy"
                        },
                        new
                        {
                            CategoryID = 9,
                            CategoryName = "Horror/Sci-fi"
                        },
                        new
                        {
                            CategoryID = 10,
                            CategoryName = "Horror/Thriller"
                        },
                        new
                        {
                            CategoryID = 11,
                            CategoryName = "Romance/Comedy"
                        },
                        new
                        {
                            CategoryID = 12,
                            CategoryName = "Romance/Drama"
                        });
                });

            modelBuilder.Entity("MovieSite.Models.ApplicationResponse", b =>
                {
                    b.HasOne("MovieSite.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
